name: c2logbook
description: A Dart wrapper providing an Object-Oriented interface to the Concept2 Logbook API 
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  http: ^1.2.0
  oauth2: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  analysis_options: any
  lints: ^2.1.0
  test: ^1.24.0
