name: c2logbook
description: A Dart wrapper providing an Object-Oriented interface to the Concept2 Logbook API 
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  freezed: ^2.4.7
  http: ^1.2.0
  oauth2_client: ^3.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
